name: pages-build-site
on:
  push:
    branches:
      - vitepress
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Yarn
        uses: mskelton/setup-yarn@v1.4.0

      - run: yarn docs:build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          exclude_assets: ""
          publish_dir: packages/docs/.vitepress/dist
          publish_branch: master
